usfirst-frc-2135/robot2025

Comp2024-Imported/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Current limit for the climber motors has been disabled for Comp-2024 imported code.
Within CTREConfig6, the stator current limit for the climber motors was disabled.
This change was required to remove the bug to be able to run the elevator.
The updated robot code was simulated with mechanism2d and the proper commands were executed. The code was also deployed into Apollo and two different days with the expected results. This change to the code does not affect any other subsystems.
Auto-formatter is not activated for phoenix CTREConfig6 class
=> disabling the climber stator current limit

Comp2025/src/main/java/frc/robot/Constants.java, Comp2025/src/main/java/frc/robot/RobotContainer.java
Enable Power and LED subsystems which were still disabled in robotContainer
Uncommented the robotContainer lines which instantiated the Power and LED subystems. This was done previously, but somehow reverted. Also removed any SysID button assignments for swerve characterization.
These subsystems were previously created and tested, but somehow disabled.
=> Instantiate Power and LED subsystems

Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
The two elevator motors have inverted directions. 
The direction of the motors did not correspond with the direction of the joystick. The new changes fix this. 
The change has been tested on the practice robot. This affects no other subsystems.
=> Inverted Elevator motor directions

Comp2025/src/main/java/frc/robot/RobotContainer.java, Comp2025/src/main/java/frc/robot/subsystems/HID.java
HID subsystem added to Comp2025 subsystems.
HID class added to subsystems section of Comp 2025 code. HID subsystem object and functionality added to Robot Container. 
This change allows robot commands to use the rumble on the game controllers. 
The HID rumble has been tested using the widgets and logs in simulation. The hid command was run using a SmartDashboard widget, and the log messages showed the correct messages. The change does not affect any other current subsystems.
=> Add hid subsystem

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Reduce AutoBuilder path following PID constants back to defaults from Apollo aggressive settings
AutoBuilder PID settings changed from 25, 0, 10 back to 10, 0 7 (P, I, D).
Apollo (2024 robot) used very aggressive PID settings in the path following control loop to attempt to improve path accuracy. Since the Comp2025 project ported these settings over, they need to be reverted back the CTRE defaults until tuned again.
- [ x Simulates with the change under test successfully working
=> Revert PathPlanner AutoBuilder path following PID constants

Comp2025/src/main/java/frc/robot/Constants.java, Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
The speeds for the coral and algae modes has been added to the manipulator. 
In addition to the set speeds and usages for the algae manipulator in the claw, the speeds and usages for the coral have also been implemented. 
The change was required for the manipulator subsystem to be able to manipulate both the coral and algae game pieces. 
The changes have been tested on the prototype manipulator. The different set speeds were tested on the coral and the algae. The code gave the expected results and worked. This code does not affect other subsystems.
=> Create manipulator claw speeds

Comp2025/src/main/java/frc/robot/Constants.java, Comp2025/src/main/java/frc/robot/RobotContainer.java
Remove 2024 AprilTag poses and replace them with 2025 Reefscape poses
Need 2025 poses for driving commands
=> Use WPILib field poses for 2025 AprilTags

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java
Merge TunerXComp values into Comp2025 TunerConstants.java.
Comp robot has an L3 swerve gearing instead of L2 on practice robot.
=> Add new tunerXComp constants to Comp2025 project

Comp2025/src/main/java/frc/robot/Constants.java, Comp2025/src/main/java/frc/robot/RobotContainer.java, Comp2025/src/main/java/frc/robot/autos/AutoLeave.java, Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Removed comments and sample code related to Crescendo game. Left one example of pathToPose for Amp in until replaced with new feature.
Several Crescendo terms were left in the code from last year that needed to be removed.
=> Remove references left over from the crescendo game

Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Button to Calibrate the Elevator when the limit switch does not function properly.
Smart Dashboard button for the calibration command was added. 
This change allows for the elevator to be calibrated if the limit switch fails to work during init. The calibration command can be run when the button is pressed during teleop. 
Code does not affect other subsystems.
=> SmartDashboard Button for Calibration Added

Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Fix rollut ratio calculation for elevator sprocket (not drum) and update all references.
Elevator movement is currently not accurate in height.
=> Fix elevator "drum" references to use a sprocket for our elevator use

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java
Added a check for the practice robot and set the wheel radius to the measured diameter divided by 2.
This allows autonomous testing on practice robot to be accurate.
=> Fix practice robot swerve wheel diameter to match worn colson wheels

Comp2025/src/main/java/frc/robot/RobotContainer.java
Enable auto commands to run in teleop by cancelling any old command and reloading auto using getAutonomousCommand.
We need to support auto commands to test during teleop. This can still fail in rare occurrences.
=> Fix auto in teleop cmd

Comp2025/src/main/java/frc/robot/RobotContainer.java
Changed the drive to facing angle heading controller to use a continuous input sensor. 
This fixes the problem seen when trying to snap to an angle, but the robot does not run continuously from 180 to -179 degrees.
=> Change heading controller to use continuous input setting to work at 180 degrees

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Update our CommandSwerveDrivetrain to add latest changes from CTRE-generated SwerveWithPathPlanner example. The update inserts two local method overrides for addVisionMeasurement to convert timestamps to the required format.
Testing has shown that the Limelight vision pose updates are not being applied to the robot pose tracked within the CommandSwerveDrivetrain subsystem.  This MAY fix the Limelight update problem.
=> Update to latest CTRE swerve generated project which has addVisionMeasurement

Comp2025/src/main/java/frc/robot/RobotContainer.java, Comp2025/src/main/java/frc/robot/commands/AcquireAlgae.java, Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java, Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java, Comp2025/src/main/java/frc/robot/subsystems/Elevator.java, Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Comp Robot Constants adjusted based on the reef. 
Config constants for the wrist rotary have been tuned. The comp robot height and manipulator angles have been adjusted based on the reef, with the robot about 1 coral away from the reef wall. PID constants have been slowed down for testing purposes. 
This change allowed the PID movements of the robot to be smoother, and for the robot to score on level 2 and 3 of the reef, assuming the robot can align one coral away from the reef. Robot PID constants have been slowed down to assist testing. 
The code was tested in the robot. This change will affect acquiring and scoring for the robot.
=> Tuning comp constants

Comp2025/src/main/java/frc/robot/commands/ScoreAlgae.java, Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java, Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Scoring Coral for Level 2 and 3 has been adjusted to new robot positioning.
Elevator heights for Branch level 2 and 3 have been adjusted for the robot against the reef. Ending height for the score coral has been adjusted. 
The change was required to score on level 2 and 3 with the new robot positioning against the reef. 
The code has been tested in the comp robot. It has been tested against the reef.
=> Tuning reef scoring

Comp2025/src/main/java/frc/robot/autos/AutoPreloadCoral.java, Comp2025/src/main/java/frc/robot/autos/AutoPreloadCoral2.java, Comp2025/src/main/java/frc/robot/autos/AutoPreloadCoral3.java
Added parallel command groups for acquire & drive
Added parallel command groups for acquire & drive
More efficient when acquiring coral during autos
=> Added parallel command groups for acquire & drive

Comp2025/src/main/deploy/elastic-layout.json, Comp2025/src/main/java/frc/robot/RobotContainer.java, Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java
Change command delay after coral is detected as expelled, since sensor triggers before the coral leaves the ejector. Also changed the default coral scoring level to L4 and updated the elastic dashboard.
Ejector was getting hung when scoring L4, because the delay was in the wrong place. Also, we now support L4 scoring in auto.
=> Add coral score delay

Comp2025/src/main/java/frc/robot/RobotContainer.java, Comp2025/src/main/java/frc/robot/subsystems/Elevator.java, Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Snap movement for aligning has been adjusted. Movements for acquiring algae have been adjusted. 
Speed and constants for the snap movement had been adjusted. Algae Acquiring height and angle on reef adjusted for new manipulator.
This change is required to acquire algae off of the reef, on level 23 and 34. Snap movements are being fixed.
Algae can now be acquired off of the reef. Snap movements are still being adjusted to be more efficient and work better.
=> Adjust snap movement and algae acquiring

Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Remove PID loop for Algae Hold state
PID loop in manipulator removed. 
This change was removed. Further testing needed in the future to implement it. 
Code has been simulated. Algae acquired as expected.
=> Remove PID loop for algae holding

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java, Comp2025/src/main/java/frc/robot/subsystems/Elevator.java, Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Added limelight pose tracking when in MegaTag1, tuned elevator heights from drive practice, increased coral ejection speed, and increased limelight std deviations relative to the tag distance.
Improvements from drive practice testing.
=> Changed LL Weightings, elevator heights, and coral expel speed

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Increase weighting of Limelight poses when updating odometry
Increased weighting is needed for more accurate autonomous modes
=> Update limelight megatag2 std deviations from testing

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Removed application of Megatag1 rotations to swerve odometry due to wackiness during drive practice. We still need to find a solution to getting Megatag2 an accurate rotation during robot setup before autonomous.
Autos were not working properly.
=> Remove MegaTag 1 application of its angle while disabled--it is broken
