Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/autos/AutoTest.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Power.java

Add TODO notes for 2025 to indicate needed changes. Changed Power subsystem file preference to use the default formatting options of the auto-formater.
Provides flags for future work to update to 2025.

Added TODO notes and fixed Power subsystem formatting

---

Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/generated/TunerConstants.java

- Fixed the 2025 Comp & Practice RoboRIO serial numbers
- Fixed 2025 Swerve X and Y

Changed RoboRIO Serial Numbers & Fix Swerve X and Y

---

Comp2025/src/main/java/frc/robot/Robot.java
Comp2025/src/main/java/frc/robot/RobotContainer.java

Adding auto file changes to comp2025

---

Comp2025/build.gradle
Comp2025/src/main/java/frc/robot/Constants.java

Updated WPIlib and chnaged the apriltag field we are using to Welded

Updating WPILib to 2025.3.1

---

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java

Changed practice robot wheel diameter to improve odometry.
Empirical measurements determined that practice robot wheel diameter is 3.65" and needed to be updated.

Changed practice bot wheel radius to match empirical measurements

---

Comp2025/src/main/java/frc/robot/Robot.java

Cleaned up commented code.
Cleanup only.

Remove old signalLogger that is unused

---

Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java

Removed current limit method of calibration, since it won't work well with chain drive. New method senses elevator down with a single limit switch while disabled. Also folded left/right heights and calibration variables into a single current height, and calibration state. Elevator motors are mechanically linked through a hex shaft unlike previous year.
Move elevator operation closer to competition methods of control.

Remove dual-side calibration and fold into a single elevator height

---

Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java

Enable elevator softlimits for robot testing.
This will protect the robot elevator mechanism should testing go out of the mechanical range.

Uncommented softlimit config code

---

Comp2025/src/main/deploy/elastic-layout.json

This contains the JSON layout file for elastic which had some old widgets in it, and we needed some of the new ones for the elevator and wrist for testing.
Easier testing and debugging over the next few weeks.
- [ x] I have updated any comments accordingly.

Add test items to elastic layout and remove unused ones

---

Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/Robot.java

Remove old name (beta) and replace it with practice bot.
Improve code readability by eliminating "beta" name.

Remove beta name and replace it with practice bot name

---

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java

Tuned the drive and steer constants for the practice bot

---

Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Pulled Ananya's work on the remote CANrange feature for detecting coral onto a separate branch. Added some comments for temporarily commented out code due to a missing algae sensor on the robot.
This feature needs to be tested and reviewed independently of the other manipulator work.

Cherry-pick of Ananya's work plus added some comments

---

Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/AcquireAlgae.java
Comp2025/src/main/java/frc/robot/commands/AcquireCoral.java
Comp2025/src/main/java/frc/robot/commands/ScoreAlgae.java
Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java
Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Adding Safe Position for the Manipulator
It puts the wrist in a safe position allowing the elevator to run up and down. It is also added in the commands/automation.

Add manipulator safeposition

---

Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/AcquireAlgae.java
Comp2025/src/main/java/frc/robot/commands/AcquireCoral.java
Comp2025/src/main/java/frc/robot/commands/ScoreAlgae.java
Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java
Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Adjust automation sequences and heights for algae and coral based on testing.
Sequences were not quite correct and needed to be updated.

Wrist manual calibration

---

Comp2025/src/main/java/frc/robot/lib/LimelightHelpers.java

Updated the limelight helpers to v1.12

---

Comp2025/src/main/java/frc/robot/Robot.java
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/lib/LimelightHelpers.java
Comp2025/src/main/java/frc/robot/subsystems/Vision.java

Updated throttle values to change if the robot is disabled

---

Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/subsystems/Vision.java

Setting the mode for the limelight IMU

---

Comp2025/src/main/java/frc/robot/subsystems/Vision.java

Changing the throttle value from 50 to 200

---

Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/Robot.java
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Comp2025/src/main/java/frc/robot/subsystems/Vision.java

Change port forwarder to handle all ports 5800-5809 to match limelight recommendation.
Limelight may use ports that we were not forwarding before this change. Other minor comment and TODO cleanup included in this change.

Update port forwarder to latest limelight recommendation

---

Comp2025/vendordeps/PathplannerLib-2025.2.5.json

Update pathplanner library

---

Comp2025/src/main/java/frc/robot/RobotContainer.java

- defer pose reset until autonomous command runs
Change pre-loading of auto in disabled periodic to only load the path from the file, but NOT reset the pose until the auto command is actually run. This prevents the field-centric orientation of the gyro from being wrong at the beginning of teleop.
Fixes the bug in field-centric orientation at the beginning of auto.

Fix robot field centric pose entering teleop

---

Comp2025/src/main/deploy/elastic-layout.json
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java

Modify the Limelight MegaTag2 standard deviations to decay with distance as recommended by the LL docs. Equations is from several other teams including Team Scream 4522.
Our standard deviations used the basic limelight example, but did not account for distance as recommended by LL docs.
THIS SHOULD BE TESTED IN THE ROBOT BEFORE MERGING!

Modify limelight std devs

---

Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Change wrist angles and elevator heights for new manipulator for scoring. Also enables elevator to go to full height.
New manipulator required new tuning angles.

Tune commands for new manipulator

---

Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/AcquireCoral.java

while true aquire coral with no timeout

---

Comp2025/build.gradle

Updated WPILib to version 2025.3.2

---

Comp2025/src/main/java/frc/robot/commands/ExpelCoral.java

Auto-formatter controls were missing in this newly added command
Readability improvement

Add missing auto-formatter controls to ExpelCoral

---

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java

Uncommenting the standard deviations on the vision measurements

---

Comp2025/src/main/java/frc/robot/commands/AcquireCoral.java
Comp2025/src/main/java/frc/robot/commands/ExpelCoral.java

Removing the rest of where the LED is called
All Instances of LED were not removed earlier causing several bugs. I fixed it with this PR.

removing LED in commands

---

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java

changed stator current

---

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java

Edited code to use MegaTag1 when disabled and MegaTag2 when enabled

---

Comp2025/src/main/deploy/pathplanner/autos/Start1_RJ_RIJ_Net.auto
Comp2025/src/main/deploy/pathplanner/autos/Start1_RJ_S1R_RK_S1R_RL.auto
Comp2025/src/main/deploy/pathplanner/autos/Start1_test1.auto
Comp2025/src/main/deploy/pathplanner/autos/Start2_RH_RGH_Net.auto
Comp2025/src/main/deploy/pathplanner/autos/Start2_RH_S1R_RK_S1R_RL.auto
Comp2025/src/main/deploy/pathplanner/autos/Start2_test2.auto
Comp2025/src/main/deploy/pathplanner/autos/Start3_RE_REF_Proc.auto
Comp2025/src/main/deploy/pathplanner/autos/Start3_RE_S2L_RD_S2L_RC.auto
Comp2025/src/main/deploy/pathplanner/autos/Start3_test3.auto
Comp2025/src/main/deploy/pathplanner/settings.json

Removed unused auto folders in PathPlanner
Remove extraneous folders

Removed unused auto folders and renumbered auto names to match chooser

---

Comp2025/src/main/java/frc/robot/Robot.java
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Comment cleanup
Comment cleanup only

Cleanup comments and remove unused imports

---

Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java

adding reject update if null statement to handle null exceptions with mt1

adding null reject update to mt1

---

Comp2025/src/main/java/frc/robot/Constants.java
Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/DrivePIDCommand.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Add a PathPlanner FollowPath command and a DrivePIDCommand as alternative auto-alignment choices
Auto-alignment is a key competitive feature if we can get it working. There are three SmartDashboard buttons that allow running these three command choices for testing. Once proven, a controller button will be assigned to execute our final choice.

Drive pid command

---

Comp2025/src/main/deploy/pathplanner/paths/RE-S2L.path
Comp2025/src/main/deploy/pathplanner/paths/Start3-RE.path
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java

updated limelight trust settings
changed global acceleration from 3.5 --> 3.8

Update vision trust

---

Comp2025/src/main/java/frc/robot/autos/AutoLeave.java
Comp2025/src/main/java/frc/robot/commands/AcquireAlgae.java
Comp2025/src/main/java/frc/robot/commands/AcquireCoral.java
Comp2025/src/main/java/frc/robot/commands/DrivePIDCommand.java
Comp2025/src/main/java/frc/robot/commands/ExpelCoral.java
Comp2025/src/main/java/frc/robot/commands/ScoreAlgae.java
Comp2025/src/main/java/frc/robot/commands/ScoreCoral.java
Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java

Fix elevator overcurrent check and remove extraneous comments
Elevator overcurrent was only checking positive threshold crossing, but down movement produces negative values. Extra comments were from LED subsystem removal.

Fix elevator overcurrent

---

Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java

Tuning Manipulator with New Encoder

Tuning Manipulator 

---

Comp2025/src/main/java/frc/robot/generated/TunerConstants.java

New tunerx values

---

Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

Fixing Manipulator safe states

fixing safe state angles

---

Comp2025/src/main/java/frc/robot/subsystems/Elevator.java

Enable gravity in elevator simulation mode
The elevator does not move downward correctly in simluation

Add gravity to elevator simulation

---

Comp2025/src/main/java/frc/robot/RobotContainer.java

Lowered kP for swerve PID alignment command and capped max velocity that can be applied from robot testing. Still needs to be tested and have more tuning in the robot.
This command created a much to aggressive robot movement to reach the desired pose, and needs to be turned down until more tuning can be done.

Adjust serve PID auto-align downward to decrease its speed from testing

---

Comp2025/elastic-layout.json
Comp2025/src/main/java/frc/robot/commands/SwervePIDController.java

Lower swerve PID auto align values  because its too aggressive.
It's too aggressive.

Lower PID values for swerve auto-align

---

Comp2025/src/main/java/frc/robot/subsystems/Vision.java

Disable Limelight IMU mode and throttle controls
Limelight pose settings were broken and needed to be regressed

Debug vision IMU mode

---

Comp2025/src/main/java/frc/robot/commands/ExpelCoral.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java
Comp2025/src/main/java/frc/robot/subsystems/Vision.java

- changed expel coral timeout
- created SetRobotPose command

Pre CVR Changes

---

Comp2025/elastic-layout.json
Comp2025/src/main/deploy/elastic-layout.json
Comp2025/src/main/deploy/pathplanner/paths/RD-S2L.path
Comp2025/src/main/deploy/pathplanner/paths/RE-REF.path
Comp2025/src/main/deploy/pathplanner/paths/RE-S2L.path
Comp2025/src/main/deploy/pathplanner/paths/REF-Proc.path
Comp2025/src/main/deploy/pathplanner/paths/RGH-Net.path
Comp2025/src/main/deploy/pathplanner/paths/RH-RGH.path
Comp2025/src/main/deploy/pathplanner/paths/RH-S1R.path
Comp2025/src/main/deploy/pathplanner/paths/RIJ-Net.path
Comp2025/src/main/deploy/pathplanner/paths/RJ-RIJ.path
Comp2025/src/main/deploy/pathplanner/paths/RJ-S1R.path
Comp2025/src/main/deploy/pathplanner/paths/RK-S1R.path
Comp2025/src/main/deploy/pathplanner/paths/S1R-RK.path
Comp2025/src/main/deploy/pathplanner/paths/S1R-RL.path
Comp2025/src/main/deploy/pathplanner/paths/S2L-RC.path
Comp2025/src/main/deploy/pathplanner/paths/S2L-RD.path
Comp2025/src/main/deploy/pathplanner/paths/Start1-L1.path
Comp2025/src/main/deploy/pathplanner/paths/Start1-RJ.path
Comp2025/src/main/deploy/pathplanner/paths/Start2-L2.path
Comp2025/src/main/deploy/pathplanner/paths/Start2-RH.path
Comp2025/src/main/deploy/pathplanner/paths/Start3-L3.path
Comp2025/src/main/deploy/pathplanner/paths/Start3-RE.path
Comp2025/src/main/deploy/pathplanner/settings.json
Comp2025/src/main/java/frc/robot/commands/ExpelCoral.java
Comp2025/src/main/java/frc/robot/lib/phoenix/CTREConfigs6.java
Comp2025/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Comp2025/src/main/java/frc/robot/subsystems/Elevator.java
Comp2025/src/main/java/frc/robot/subsystems/Manipulator.java

- Changed elevator heights and angles for L4
- changed processor angles and heights
- added autonomous 2 tab in elastic
- increased elevator kP
- slowed down autos

CVR Practice Day Changes

---

Comp2025/src/main/java/frc/robot/RobotContainer.java
Comp2025/src/main/java/frc/robot/commands/AcquireAlgae.java

Fixing algae command

---

Comp2025/src/main/java/frc/robot/subsystems/Vision.java

- [X ] Compiles with no errors and no ***additional*** warnings
- [X ] Simulates without crashes, errors or warnings
- [X ] Simulates with the change under test successfully working
- [ X] Tested in the robot with no crashes, errors or warnings
- [ X] I verified the log messages were as expected with no warnings in AdvantageScope
- [X ] New feature (non-breaking change which adds functionality)
- [X ] The auto-formatter was working correctly when submitted
- [ X] I have updated any comments accordingly.

Reimplemented throttle values for limelight
